---
# Server Manajer - Install MySQL DB
- name: "install database app"
  apt: name={{ item }}
  loop:
    - mysql-client
    - mysql-server
  tags:
    - mysql-install

# Server Manajer - Config MySQL DB
- name: "sets the root password"
  no_log: true
  mysql_user:
    name: "{{ mysql_root_username }}"
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - mysql-install

- name: "removes all anonymous user accounts"
  no_log: true
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - mysql-install

- name: "removes the test database"
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - mysql-install

# Server Manajer - Config MySQL DB
- name: "start service"
  systemd:
    state: started
    name: mysql
  tags:
    - mysql-install

# Server Manajer - Create MySQL DB
- name: "create database app"
  no_log: true
  mysql_db:
    name: "{{ app_database }}"
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - mysql-create-db

- name: "create database user"
  no_log: true
  mysql_user:
    name: "{{ app_username }}"
    password: "{{ app_password }}"
    priv: "{{ app_database }}.*:ALL"
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - mysql-create-db

# Server Manajer - Delete MySQL DB
- name: "delete database app"
  no_log: true
  mysql_db:
    name: "{{ app_database }}"
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - mysql-delete-db

- name: "delete database user"
  no_log: true
  mysql_user:
    name: "{{ app_username }}"
    password: "{{ app_password }}"
    priv: "{{ app_database }}.*:ALL"
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - mysql-delete-db