---
# Server Manajer - Install PHP
- name: "install requirements"
  apt: name={{ item }}
  loop:
    - php7.4
    - php7.4-fpm
    - php7.4-common
    - php7.4-mysql
    - php7.4-curl 
    - php7.4-gd 
    - php7.4-mbstring 
    - php7.4-gettext
    - php7.4-xml 
    - php7.4-xmlrpc 
    - php7.4-soap 
    - php7.4-intl 
    - php7.4-zip
    - libapache2-mod-php7.4
  tags:
    - php-install

- name: "copy info.php"
  copy: 
    src: "{{ item }}"
    dest: "/var/www/"
  with_items:
    - info.php
  tags:
    - php-install